server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
#        Mysql数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#    redis缓存
  redis:
    host: 127.0.0.1
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
#  链路追踪
  sleuth:
    sampler:
#      0-1之间的取值 1代表全部 0.1代表10%
      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml  #读取映射文件
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
   db-config:
     id-type: auto  #默认使用数据库自增
feign:
  sentinel:
    enabled: true
